version: "3.9"

networks:
  test_network:
    driver: bridge

volumes:
  postgres_data:

services:

  # ----------------- SELENIUM GRID HUB -----------------
  hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    shm_size: 256mb
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - test_network
    environment:
      - GRID_TIMEOUT=300000
      - GRID_BROWSER_TIMEOUT=300000
    restart: unless-stopped

  # ----------------- CHROME NODE -----------------
  chrome:
    image: selenium/node-chrome:latest
    container_name: chrome-node
    shm_size: 512mb
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - VNC_NO_PASSWORD=1
    networks:
      - test_network
    restart: unless-stopped

  # ----------------- CHROME VIDEO -----------------
  chrome_video:
    image: selenium/video:ffmpeg-4.3.1-20221219
    container_name: chrome-video
    shm_size: 256mb
    volumes:
      - /tmp/videos:/videos
    depends_on:
      - chrome
    environment:
      - DISPLAY_CONTAINER_NAME=chrome-node
      - SCREEN_WIDTH=1360
      - SCREEN_HEIGHT=1020
      - FILE_NAME=chrome_video.mp4
    networks:
      - test_network
    restart: unless-stopped

  # ----------------- POSTGRES DATABASE -----------------
  postgres-db:
    image: postgres
    container_name: postgres-db
    env_file:
      - .env_db
    networks:
      - test_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5435:5432'
    restart: always

  # ----------------- SPRING BOOT APP -----------------
  spring-app:
    image: spring-app:latest
    container_name: spring-app
    env_file:
      - .env_app
    networks:
      - test_network
    ports:
      - '8000:8000'
    depends_on:
      postgres-db:
        condition: service_started
